version: '3'
services:
   jenkins:
     container_name: jenkins
     image: jenkins/jenkins
     build:
       context: jenkins
     ports:
       - "8080:8080"
     volumes:
       - "$PWD/jenkins_home:/var/jenkins_home"
     networks:
       - net
   remote_host1:
     container_name: remote-host1
     image: remote-host1
     build:
       context: centos
     networks:
       - net
   remote_host2:
     container_name: remote-host2
     image: remote-host2
     build:
       context: ubuntu
     networks:
       - net
networks:
   net:
